DROP DATABASE IF EXISTS DISCORD;
CREATE DATABASE DISCORD;
USE DISCORD;

CREATE TABLE CLIENT(
	ID_CLIENT	INT(5)		NOT NULL	AUTO_INCREMENT,
	NOM		VARCHAR(40)	NOT NULL,
	EMAIL		VARCHAR(40)	NOT NULL,
PRIMARY KEY (ID_CLIENT)
);


CREATE TABLE SERVER(
	ID_SERVER	VARCHAR(20)	NOT NULL,
	CLIENTSERVER	INT(5)	NOT NULL,
	SUBSCRIPTION	TINYINT(1)	NOT NULL,
PRIMARY KEY (ID_SERVER),
CONSTRAINT FK1 FOREIGN KEY (CLIENTSERVER) REFERENCES CLIENT(ID_CLIENT) ON DELETE CASCADE
);


CREATE TABLE SERVERUSER(
	ID_USER		VARCHAR(20)	NOT NULL,
	ID_SERVER	VARCHAR(20)	NOT NULL,
	USERPASSWORD	VARCHAR(30)	NOT NULL,
	USERPOINT	VARCHAR(5)	NOT NULL,
PRIMARY KEY (ID_USER),
CONSTRAINT FOREIGN KEY (ID_SERVER) REFERENCES SERVER(ID_SERVER) ON DELETE CASCADE
);


CREATE TABLE ACHIVEMENT(
	ID_ACHIVEMENT	INT(5)		NOT NULL	AUTO_INCREMENT,
	DESCRIPTION	VARCHAR(100)	NOT NULL,
	NOM		VARCHAR(30)	NOT NULL,
PRIMARY KEY (ID_ACHIVEMENT)
);


CREATE TABLE USERACHIVEMENT(
	ID_ACHIVEMENT	INT(5)		NOT NULL,
	ID_USER		VARCHAR(20)	NOT NULL,
CONSTRAINT FOREIGN KEY (ID_USER) REFERENCES SERVERUSER(ID_USER) ON DELETE CASCADE,
INDEX (ID_USER),
CONSTRAINT FOREIGN KEY (ID_ACHIVEMENT) REFERENCES ACHIVEMENT(ID_ACHIVEMENT) ON DELETE CASCADE
);


CREATE VIEW USERLEADERBOARD AS
SELECT SERVERUSER.ID_USER, USERPOINT, COUNT(ID_ACHIVEMENT) 
FROM SERVERUSER INNER JOIN USERACHIVEMENT ON SERVERUSER.ID_USER = USERACHIVEMENT.ID_USER
ORDER BY SERVERUSER.ID_USER ASC;
