USE DISCORD;

DELETE FROM CLIENT WHERE EMAIL = 'JohnDoe@mail.com';

INSERT INTO CLIENT (NOM, EMAIL)
VALUES ('John Doe', 'JohnDoe@mail.com'); 

INSERT INTO SERVER (ID_SERVER, CLIENTSERVER, SUBSCRIPTION)
VALUES ('CoMpl3xId--/*', (SELECT ID_CLIENT FROM CLIENT WHERE EMAIL = 'JohnDoe@mail.com'), 0);

INSERT INTO SERVERUSER (ID_USER, ID_SERVER, USERPASSWORD, USERPOINT)
VALUES ('JohnDoe', 'CoMpl3xId--/*', 'FooBar', 0);

DELETE FROM ACHIVEMENT WHERE NOM = 'FooBar';

INSERT INTO ACHIVEMENT(DESCRIPTION, NOM) 
VALUES ('Testing a MoistyBot!', 'FooBar');

INSERT INTO USERACHIVEMENT(ID_ACHIVEMENT, ID_USER)
VALUES ((SELECT ID_ACHIVEMENT FROM ACHIVEMENT WHERE NOM = 'FooBar'), 'JohnDoe');
